class WrongException(Exception):
    pass
class NouFoundException(Exception):
    pass
